.TH "BLL" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLL
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDashboardStatisticsService\fP"
.br
.ti -1c
.RI "class \fBUserService\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
