.TH "BLL.UserService" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLL.UserService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP? \fBValidateLogin\fP (string username, string password)"
.br
.RI "Validates the login credentials of a user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBUserService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBUser\fP? BLL\&.UserService\&.ValidateLogin (string username, string password)"

.PP
Validates the login credentials of a user\&. 
.PP
\fBParameters\fP
.RS 4
\fIusername\fP Username of the user
.br
\fIpassword\fP Password of the user
.RE
.PP
\fBReturns\fP
.RS 4
Return the user that haves the username and the password and in the case that not have a user with the user and password returns null\&.
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBUserService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
