.TH "DAL" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAL
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTicketFactory\fP"
.br
.RI "Class for the creation of tickets using the Factory pattern\&. "
.ti -1c
.RI "class \fBTicketManagement\fP"
.br
.RI "Class for managing tickets in the database\&. "
.ti -1c
.RI "class \fBUserManagement\fP"
.br
.RI "Class for managing user authentication and roles in the database\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
