.TH "Models.SoftwareTicket" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models.SoftwareTicket \- Represents a software-related ticket in the Ticket2Help system\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModels\&.Ticket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetSummary\fP ()"
.br
.RI "Gets a summary of the software ticket\&. "
.in -1c

Public Member Functions inherited from \fBModels\&.Ticket\fP
.in +1c
.ti -1c
.RI "string \fBGetSummary\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSoftware\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the software involved in the software ticket and the description of the issue\&. "
.ti -1c
.RI "string \fBDescription\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the description of the issue in the software ticket\&. "
.in -1c

Properties inherited from \fBModels\&.Ticket\fP
.in +1c
.ti -1c
.RI "int \fBId\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the unique identifier for the ticket\&. "
.ti -1c
.RI "string \fBUsername\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the username of the user who created the ticket\&. "
.ti -1c
.RI "string \fBTicketType\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the type of the ticket, which can be 'Hardware' or 'Software'\&. "
.ti -1c
.RI "DateTime \fBCreatedAt\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the date and time when the ticket was created\&. "
.ti -1c
.RI "DateTime \fBAnsweredAt\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the date and time when the ticket was answered\&. "
.ti -1c
.RI "string \fBStatus\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the status of the ticket, which can be 'Unanswered', 'In Service', or 'Fulfilled'\&. "
.ti -1c
.RI "string \fBServiceStatus\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the service status of the ticket, which can be 'Open', 'Resolved', or 'Not Resolved'\&. "
.ti -1c
.RI "string \fBResponse\fP\fR [get, set]\fP"
.br
.RI "Response for the ticket\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a software-related ticket in the Ticket2Help system\&. 
.PP
Definition at line \fB85\fP of file \fBTicket\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Models\&.SoftwareTicket\&.GetSummary ()"

.PP
Gets a summary of the software ticket\&. 
.PP
\fBReturns\fP
.RS 4
The sumary of the hardware tickets
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBTicket\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Models\&.SoftwareTicket\&.Description\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the description of the issue in the software ticket\&. 
.PP
Definition at line \fB95\fP of file \fBTicket\&.cs\fP\&.
.SS "string Models\&.SoftwareTicket\&.Software\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the software involved in the software ticket and the description of the issue\&. 
.PP
Definition at line \fB90\fP of file \fBTicket\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
