.TH "Models.User" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models.User \- Represents a user in the Ticket2Help system\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUsername\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the username of the user\&. "
.ti -1c
.RI "string \fBRole\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the role of the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a user in the Ticket2Help system\&. 
.PP
Definition at line \fB12\fP of file \fBUser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Models\&.User\&.Role\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the role of the user\&. 
.PP
Definition at line \fB21\fP of file \fBUser\&.cs\fP\&.
.SS "string Models\&.User\&.Username\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the username of the user\&. 
.PP
Definition at line \fB17\fP of file \fBUser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
