.TH "PA_WPF_DB.TechnicianDashboard" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.TechnicianDashboard \- \fBTechnicianDashboard\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, and System\&.Windows\&.Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTechnicianDashboard\fP\&. 

Interaction logic for TechnicianDashboard\&.xaml\&. 
.PP
Definition at line \fB42\fP of file \fBTechnicianDashboard\&.g\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PA_WPF_DB\&.TechnicianDashboard\&.TechnicianDashboard ()"

.PP
Definition at line \fB27\fP of file \fBTechnicianDashboard\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.TechnicianDashboard\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB59\fP of file \fBTechnicianDashboard\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.TechnicianDashboard\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB59\fP of file \fBTechnicianDashboard\&.g\&.i\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
