.TH "PA_WPF_DB" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml\&. "
.ti -1c
.RI "class \fBDashboardWindow\fP"
.br
.RI "Interaction logic for DashboardWindow\&.xaml\&. "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fBMainWindow\fP\&. "
.ti -1c
.RI "class \fBNewTicketWindow\fP"
.br
.RI "Lógica de interacción para NewTicket\&.xaml\&. "
.ti -1c
.RI "class \fBTechnicianDashboard\fP"
.br
.RI "\fBTechnicianDashboard\fP\&. "
.ti -1c
.RI "class \fBTechnicianResponseWindow\fP"
.br
.RI "\fBTechnicianResponseWindow\fP\&. "
.ti -1c
.RI "class \fBUserDashboard\fP"
.br
.RI "\fBUserDashboard\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
