.TH "PA_WPF_DB.DashboardWindow" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.DashboardWindow \- Interaction logic for DashboardWindow\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "SeriesCollection \fBServiceStatusSeries\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "SeriesCollection \fBAverageTimeSeries\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string[] \fBTimeLabels\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFulfilledPercentageText\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for DashboardWindow\&.xaml\&. 

\fBDashboardWindow\fP\&. 
.PP
Definition at line \fB15\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PA_WPF_DB\&.DashboardWindow\&.DashboardWindow ()"

.PP
Definition at line \fB25\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.DashboardWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB67\fP of file \fBDashboardWindow\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.DashboardWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB67\fP of file \fBDashboardWindow\&.g\&.i\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "SeriesCollection PA_WPF_DB\&.DashboardWindow\&.AverageTimeSeries\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.
.SS "string PA_WPF_DB\&.DashboardWindow\&.FulfilledPercentageText\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB23\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.
.SS "SeriesCollection PA_WPF_DB\&.DashboardWindow\&.ServiceStatusSeries\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.
.SS "string [] PA_WPF_DB\&.DashboardWindow\&.TimeLabels\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBDashboardWindow\&.xaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
