.TH "PA_WPF_DB.App" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.App \- Interaction logic for App\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application, System\&.Windows\&.Application, System\&.Windows\&.Application, and System\&.Windows\&.Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml\&. 

\fBApp\fP\&. 
.PP
Definition at line \fB10\fP of file \fBApp\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.App\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB49\fP of file \fBApp\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.App\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB49\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.SS "void PA_WPF_DB\&.App\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB49\fP of file \fBApp\&.g\&.cs\fP\&.
.SS "static void PA_WPF_DB\&.App\&.Main ()\fR [static]\fP"

.PP
Application Entry Point\&. 
.PP
Definition at line \fB64\fP of file \fBApp\&.g\&.cs\fP\&.
.SS "static void PA_WPF_DB\&.App\&.Main ()\fR [static]\fP"

.PP
Application Entry Point\&. 
.PP
Definition at line \fB64\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.SS "static void PA_WPF_DB\&.App\&.Main ()\fR [static]\fP"

.PP
Application Entry Point\&. 
.PP
Definition at line \fB64\fP of file \fBApp\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
