.TH "PA_WPF_DB.MainWindow" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.MainWindow \- \fBMainWindow\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBMainWindow\fP\&. 
.PP
Definition at line \fB20\fP of file \fBMainWindow\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PA_WPF_DB\&.MainWindow\&.MainWindow ()"

.PP
Definition at line \fB22\fP of file \fBMainWindow\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB67\fP of file \fBMainWindow\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB67\fP of file \fBMainWindow\&.g\&.i\&.cs\fP\&.
.SS "void PA_WPF_DB\&.MainWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB67\fP of file \fBMainWindow\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
