.TH "PA_WPF_DB.TechnicianResponseWindow" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.TechnicianResponseWindow \- \fBTechnicianResponseWindow\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, and System\&.Windows\&.Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "\fBTechnicianResponseWindow\fP (int ticketId)"
.br
.RI "Constructor for \fBTechnicianResponseWindow\fP that initializes the window with the ticket ID to respond to\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTechnicianResponseWindow\fP\&. 

Interaction logic for TechnicianResponseWindow\&.xaml\&. 
.PP
Definition at line \fB42\fP of file \fBTechnicianResponseWindow\&.g\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PA_WPF_DB\&.TechnicianResponseWindow\&.TechnicianResponseWindow (int ticketId)"

.PP
Constructor for \fBTechnicianResponseWindow\fP that initializes the window with the ticket ID to respond to\&. 
.PP
\fBParameters\fP
.RS 4
\fIticketId\fP The ID of the ticket to build
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBTechnicianResponseWindow\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.TechnicianResponseWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB59\fP of file \fBTechnicianResponseWindow\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.TechnicianResponseWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB59\fP of file \fBTechnicianResponseWindow\&.g\&.i\&.cs\fP\&.
.SS "void PA_WPF_DB\&.TechnicianResponseWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB59\fP of file \fBTechnicianResponseWindow\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
