.TH "PA_WPF_DB.NewTicketWindow" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PA_WPF_DB.NewTicketWindow \- Lógica de interacción para NewTicket\&.xaml\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewTicketWindow\fP (string username)"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent\&. "
.in -1c
.SH "Detailed Description"
.PP 
Lógica de interacción para NewTicket\&.xaml\&. 

\fBNewTicketWindow\fP\&. 
.PP
Definition at line \fB23\fP of file \fBNewTicket\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PA_WPF_DB\&.NewTicketWindow\&.NewTicketWindow (string username)"

.PP
Definition at line \fB28\fP of file \fBNewTicket\&.xaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PA_WPF_DB\&.NewTicketWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB106\fP of file \fBNewTicket\&.g\&.cs\fP\&.
.SS "void PA_WPF_DB\&.NewTicketWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB106\fP of file \fBNewTicket\&.g\&.i\&.cs\fP\&.
.SS "void PA_WPF_DB\&.NewTicketWindow\&.InitializeComponent ()"

.PP
InitializeComponent\&. 
.PP
Definition at line \fB106\fP of file \fBNewTicket\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
