.TH "Tests" 3 "TICKET2HELP MANAGEMENT PLATFORM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTicketTests\fP"
.br
.RI "Unit tests for the \fBTicket\fP, \fBHardwareTicket\fP, and \fBSoftwareTicket\fP classes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TICKET2HELP MANAGEMENT PLATFORM from the source code\&.
